# https://docs.spring.io/spring-boot/docs/2.0.0.RELEASE/reference/htmlsingle/#common-application-properties
server:
  port: 9010
  servlet:
    context-path: /

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://106.15.89.145:3306/admin3?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456

  # JSON
  jackson:
    locale: zh_CN
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

# LOGGING
logging:
  config: 'classpath:logback.xml'

hbase:
  zk-quorum: dyl-171,dyl-172,dyl-173
  data-table: dyl:bd_buoy

kafka:
  broker-list: dyl-171:9092,dyl-172:9092,dyl-173:9092
  raw-topic: bd_buoy