server:
  port: 8080
  servlet:
    context-path: /

# SPRING
spring:

  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/beidou?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: 123456

# LOGGING
logging:
  config: 'classpath:logback.xml'