server:
  port: 9011
  servlet:
    context-path: /

# SPRING
spring:
  # DATASOURCE
  datasource:
    primary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: 'jdbc:mysql://192.168.1.51:3306/beidou?useUnicode=true&characterEncoding=UTF-8'
      username: root
      password: 123456

    secondary:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: 'jdbc:mysql://106.15.89.145:3306/admin3?useUnicode=true&characterEncoding=UTF-8'
      username: root
      password: 123456

# LOGGING
logging:
  config: 'classpath:logback.xml'

kafka:
  broker-list: tdyl-171:9092,dyl-172:9092,dyl-173:9092
  bd-topic: bd_buoy